# Generated by Django 4.2.16 on 2026-05-24 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0019_store_checkin_rotation_minutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RotatingCheckinKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=16, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkin_keys",
                        to="core.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["store", "expires_at"], name="rck_store_expires_idx"),
                    models.Index(
                        fields=["store", "superseded_at"], name="rck_store_superseded_idx"
                    ),
                ],
            },
        ),
    ]
