"""
Web-chat channel adapter.

This is the first concrete adapter and it preserves the existing
`POST /api/conversations/{id}/messages/` SSE shape byte-for-byte —
the new abstraction is opt-in plumbing on the inbound side; the
streaming response is generated by the existing `_run_agent_stream`
helper exactly as before.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from .base import ChannelAdapter, NormalizedMessage


class WebChatAdapter(ChannelAdapter):
    channel = "web_chat"

    def normalize_inbound(
        self,
        payload: dict,
        headers: Mapping[str, str] | None = None,
    ) -> NormalizedMessage:
        text = (payload.get("content") or "").strip()
        rag = payload.get("rag_chunks") or []
        if not isinstance(rag, list):
            rag = []
        return NormalizedMessage(
            text=text,
            customer_identifier="",  # carried on the parent Conversation row
            channel=self.channel,
            rag_chunks=rag,
            raw_payload=payload,
        )

    def format_outbound(
        self,
        reply_text: str,
        metadata: Mapping[str, Any] | None = None,
    ) -> dict:
        """Returns the canonical `done` SSE event payload shape.

        Unused by the streaming view (which emits each token incrementally),
        but kept for parity so a test or a non-streaming caller can drive
        the adapter end to end.
        """
        meta = metadata or {}
        return {
            "message_id": meta.get("message_id"),
            "text": reply_text,
            "booking_id": meta.get("booking_id"),
            "iteration_count": meta.get("iteration_count", 0),
        }
