# Generated by Django 4.2.16 on 2026-05-24 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0012_conversation_store"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                ("stackable", models.BooleanField(default=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("peak_hours", "Peak hours"),
                            ("day_of_week", "Day of week"),
                            ("member_tier", "Member tier"),
                            ("min_duration", "Minimum duration"),
                            ("bracket_rate", "Bracket rate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("params", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applies_to_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="core.resource",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="core.store",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "id"],
                "indexes": [
                    models.Index(
                        fields=["store", "enabled"], name="pricing_rule_store_enabled_idx"
                    ),
                    models.Index(fields=["store", "rule_type"], name="pricing_rule_store_type_idx"),
                ],
            },
        ),
    ]
