/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all resources
         * @description Returns every resource in the store. Filter by `type` to narrow results.
         */
        get: operations["listResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a single resource */
        get: operations["getResource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources/{id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get open slots for a resource on a given date
         * @description Computes open time slots from business hours minus existing bookings.
         *     Returns both confirmed-free slots (`available`) and suggested nearby slots
         *     when the requested time is taken (`suggestions`).
         */
        get: operations["getResourceAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bookings */
        get: operations["listBookings"];
        put?: never;
        /**
         * Create a booking
         * @description Creates a new booking. The database enforces overlap prevention with
         *     `EXCLUDE USING gist(resource_id WITH =, tstzrange(start_time, end_time) WITH &&)`.
         *     Returns `409` when a concurrent request claims the same slot.
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a single booking */
        get: operations["getBooking"];
        put?: never;
        post?: never;
        /** Cancel / delete a booking */
        delete: operations["deleteBooking"];
        options?: never;
        head?: never;
        /**
         * Partially update a booking
         * @description Modify start/end time or status. Overlap rules still apply when time is changed;
         *     returns `409` on conflict.
         */
        patch: operations["updateBooking"];
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a new AI conversation session */
        post: operations["createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve conversation with message history */
        get: operations["getConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a user message and stream the assistant response
         * @description Accepts a user message and kicks off the agent loop. The response is
         *     a **Server-Sent Events** stream (`text/event-stream`).
         *
         *     See `sse-protocol.md` for the full event-type reference.
         *
         *     The stream ends with a `done` event containing the final
         *     `booking_id` (if a booking was created) and the complete assistant text.
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** [Staff] List all conversations */
        get: operations["adminListConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** [Staff] List all bookings sorted by created_at desc */
        get: operations["adminListBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description - `console` — a dedicated gaming console station (PS5 / Switch)
         *     - `room`    — a private room with console(s) and seating
         *     - `table`   — a board-game table
         * @enum {string}
         */
        ResourceType: "console" | "room" | "table";
        /**
         * @description - `pending`         — created, awaiting confirmation
         *     - `pending_payment` — Stripe Checkout session opened; expires after TTL
         *     - `confirmed`       — payment received / manually confirmed
         *     - `cancelled`       — cancelled by customer or staff
         * @enum {string}
         */
        BookingStatus: "pending" | "pending_payment" | "confirmed" | "cancelled";
        /**
         * @description Whether the booking was made through the manual form or the AI agent
         * @enum {string}
         */
        BookingSource: "manual" | "agent";
        Resource: {
            readonly id: number;
            store_id: number;
            type: components["schemas"]["ResourceType"];
            /** @example PS5 Station A */
            name: string;
            /** @example 4 */
            capacity: number;
            /**
             * Format: decimal
             * @description CNY per hour, stored as a decimal string to avoid float rounding
             * @example 58.00
             */
            price_per_hour: string;
            /**
             * @description Freeform JSON — controller count, included peripherals, etc.
             * @example {
             *       "controller_count": 2,
             *       "has_vr": false,
             *       "titles": [
             *         "Elden Ring",
             *         "FIFA 25"
             *       ]
             *     }
             */
            metadata?: {
                [key: string]: unknown;
            };
        };
        PaginatedResources: {
            count: number;
            /** Format: uri */
            next?: string | null;
            /** Format: uri */
            previous?: string | null;
            results: components["schemas"]["Resource"][];
        };
        TimeSlot: {
            /**
             * Format: date-time
             * @example 2026-06-01T14:00:00+08:00
             */
            start: string;
            /**
             * Format: date-time
             * @example 2026-06-01T16:00:00+08:00
             */
            end: string;
        };
        AvailabilityResponse: {
            resource_id: number;
            /**
             * Format: date
             * @example 2026-06-01
             */
            date: string;
            /** @description Confirmed-free continuous time blocks for the requested date */
            available: components["schemas"]["TimeSlot"][];
            /**
             * @description Nearby alternative slots when the caller's requested time is taken
             *     (same day ±1 h; same time next available day). Empty when `available`
             *     covers the entire requested window.
             */
            suggestions: components["schemas"]["TimeSlot"][];
        };
        Booking: {
            readonly id: number;
            resource_id: number;
            /** @description Set when the booking was created by the AI agent */
            conversation_id?: number | null;
            /** @example Alice Wang */
            customer_name: string;
            /** @example +86-138-0000-0000 */
            customer_phone: string;
            /**
             * Format: date-time
             * @example 2026-06-01T20:00:00+08:00
             */
            start_time: string;
            /**
             * Format: date-time
             * @example 2026-06-01T22:00:00+08:00
             */
            end_time: string;
            status: components["schemas"]["BookingStatus"];
            source: components["schemas"]["BookingSource"];
            /** @description Stripe Checkout session ID (populated when status=pending_payment) */
            stripe_session_id?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        BookingCreate: {
            resource_id: number;
            conversation_id?: number | null;
            customer_name: string;
            customer_phone: string;
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
            source?: components["schemas"]["BookingSource"];
        };
        /** @description All fields optional; only supplied fields are updated. */
        BookingPatch: {
            /** Format: date-time */
            start_time?: string;
            /** Format: date-time */
            end_time?: string;
            status?: components["schemas"]["BookingStatus"];
            customer_name?: string;
            customer_phone?: string;
        };
        PaginatedBookings: {
            count: number;
            /** Format: uri */
            next?: string | null;
            /** Format: uri */
            previous?: string | null;
            results: components["schemas"]["Booking"][];
        };
        Conversation: {
            readonly id: number;
            /** @description Browser fingerprint, session token, or phone number */
            customer_identifier: string;
            /** Format: date-time */
            readonly started_at: string;
            /** @enum {string} */
            status: "active" | "closed";
        };
        ConversationCreate: {
            /** @description Optional; server generates a UUID if omitted */
            customer_identifier?: string;
        };
        ConversationDetail: components["schemas"]["Conversation"] & {
            messages?: components["schemas"]["Message"][];
        };
        Message: {
            readonly id: number;
            conversation_id: number;
            /** @enum {string} */
            role: "user" | "assistant" | "tool";
            content: string;
            /** @description Serialized tool call request + result (JSONB in the DB) */
            tool_call_data?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        MessageCreate: {
            /** @example I'd like to book PS5 Station A on Saturday 8 pm for 2 hours */
            content: string;
        };
        PaginatedConversations: {
            count: number;
            /** Format: uri */
            next?: string | null;
            /** Format: uri */
            previous?: string | null;
            results: components["schemas"]["Conversation"][];
        };
        ErrorDetail: {
            /** @example Not found. */
            detail: string;
        };
        /**
         * @description DRF-style validation error map. Keys are field names; values are arrays of
         *     error strings. A `non_field_errors` key carries form-level errors.
         * @example {
         *       "start_time": [
         *         "This field is required."
         *       ],
         *       "end_time": [
         *         "end_time must be after start_time."
         *       ]
         *     }
         */
        ValidationErrors: {
            [key: string]: string[];
        };
        ConflictError: {
            /** @example The requested time slot is already booked. */
            detail: string;
            /** @description ID of the booking that occupies the slot, if known */
            conflicting_booking_id: number | null;
            /** @description Alternative slots from conflict-aware suggestion logic */
            suggestions?: components["schemas"]["TimeSlot"][];
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorDetail"];
            };
        };
        /** @description Request body failed validation */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrors"];
            };
        };
        /** @description Staff authentication required */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorDetail"];
            };
        };
    };
    parameters: {
        PathId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listResources: {
        parameters: {
            query?: {
                /** @description Filter by resource type */
                type?: components["schemas"]["ResourceType"];
                store_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of resources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResources"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    getResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getResourceAvailability: {
        parameters: {
            query: {
                /** @description Date to check in YYYY-MM-DD format (store's local timezone) */
                date: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Availability result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
        };
    };
    listBookings: {
        parameters: {
            query?: {
                resource_id?: number;
                status?: components["schemas"]["BookingStatus"];
                /** @description Filter by start-time date (YYYY-MM-DD) */
                date?: string;
                source?: components["schemas"]["BookingSource"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of bookings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBookings"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description Booking created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Time slot already booked (DB-level overlap rejection) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
        };
    };
    getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingPatch"];
            };
        };
        responses: {
            /** @description Updated booking */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            /** @description Updated time conflicts with an existing booking */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
        };
    };
    createConversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Conversation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description SSE stream of assistant events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example event: token
                     *     data: {"delta":"Sure"}
                     *
                     *     event: done
                     *     data: {"message_id":42,"booking_id":null,"text":"Sure!"}
                     */
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
        };
    };
    adminListConversations: {
        parameters: {
            query?: {
                status?: "active" | "closed";
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated conversations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedConversations"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    adminListBookings: {
        parameters: {
            query?: {
                status?: components["schemas"]["BookingStatus"];
                resource_id?: number;
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated bookings (newest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBookings"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
}
