# Generated by Django 4.2.16 on 2026-05-23 05:15

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def backfill_store_slugs(apps, schema_editor):
    """Populate Store.slug from Store.name for existing rows.

    Collision-safe: when two stores slugify to the same value, the second
    one gets a `-2`, `-3`, ... suffix. Idempotent — re-running leaves
    already-slugged rows alone.
    """
    Store = apps.get_model("core", "Store")
    used = set(Store.objects.exclude(slug="").values_list("slug", flat=True))
    for store in Store.objects.filter(slug=""):
        base = slugify(store.name) or f"store-{store.pk}"
        candidate = base
        n = 2
        while candidate in used:
            candidate = f"{base}-{n}"
            n += 1
        store.slug = candidate
        store.save(update_fields=["slug"])
        used.add(candidate)


def noop_reverse(apps, schema_editor):
    Store = apps.get_model("core", "Store")
    Store.objects.update(slug="")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_backfill_booking_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="brand",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="store",
            name="slug",
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
        migrations.RunPython(backfill_store_slugs, reverse_code=noop_reverse),
        migrations.CreateModel(
            name="QRAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("review", "Google review"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("rednote", "RedNote"),
                            ("wechat", "WeChat"),
                            ("wifi", "Store WiFi"),
                            ("custom", "Custom"),
                        ],
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("target_url", models.URLField(max_length=500)),
                ("position", models.PositiveIntegerField()),
                ("reward_points", models.PositiveIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_actions",
                        to="core.store",
                    ),
                ),
            ],
            options={
                "ordering": ["store", "position"],
            },
        ),
        migrations.CreateModel(
            name="QREvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(choices=[("scan", "Scan"), ("click", "Click")], max_length=8),
                ),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("locale", models.CharField(blank=True, max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="core.qraction",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qr_events",
                        to="core.customer",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_events",
                        to="core.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "-created_at"], name="core_qreven_store_i_160338_idx"
                    ),
                    models.Index(
                        fields=["action", "-created_at"], name="core_qreven_action__621487_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="qraction",
            constraint=models.UniqueConstraint(
                fields=("store", "position"), name="qraction_unique_store_position"
            ),
        ),
    ]
