# Generated by Django 4.2.16 on 2026-05-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_qr_actions_and_store_branding"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="channel",
            field=models.CharField(
                choices=[
                    ("web_chat", "Web chat"),
                    ("sms", "SMS"),
                    ("whatsapp", "WhatsApp"),
                    ("phone", "Phone"),
                    ("manual_staff", "Staff (manual)"),
                ],
                default="web_chat",
                max_length=16,
            ),
        ),
    ]
