# Generated by Django 4.2.16 on 2026-05-23 15:32

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_conversation_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="quiet_hours_end",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name="store",
            name="quiet_hours_start",
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
    ]
