# Generated by Django 4.2.16 on 2026-05-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_memberships"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("pending_payment", "Pending Payment"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
