# Generated by Django 4.2.16 on 2026-05-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_store_quiet_hours_end_store_quiet_hours_start'),
        ('core', '0010_backfill_points'),
    ]

    operations = [
    ]
