# Generated by Django 4.2.16 on 2026-05-24 11:56

from decimal import Decimal

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_conversation_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="deposit_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not required"),
                    ("pending_payment", "Pending payment"),
                    ("deposit_paid", "Deposit paid"),
                    ("paid_in_full", "Paid in full"),
                    ("refunded", "Refunded"),
                    ("partially_refunded", "Partially refunded"),
                ],
                default="not_required",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="deposit_override_mode",
            field=models.CharField(
                blank=True,
                choices=[("none", "None"), ("percentage", "Percentage"), ("fixed", "Fixed")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="deposit_override_value",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="store",
            name="deposit_mode",
            field=models.CharField(
                choices=[("none", "None"), ("percentage", "Percentage"), ("fixed", "Fixed")],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="deposit_value",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="store",
            name="refund_matrix",
            field=models.JSONField(default=core.models.default_refund_matrix),
        ),
        migrations.AddField(
            model_name="store",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="stripe_charges_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
