# Generated by Django 4.2.16 on 2026-05-24 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_conversation_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="cancellation_lead_hours",
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.CreateModel(
            name="CustomerOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone", models.CharField(max_length=32)),
                ("code", models.CharField(max_length=6)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_otps",
                        to="core.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone", "store", "-created_at"],
                        name="core_custom_phone_40c4ff_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerLoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone", models.CharField(max_length=32)),
                ("success", models.BooleanField(default=False)),
                ("ip_address", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_login_attempts",
                        to="core.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone", "store", "-created_at"],
                        name="core_custom_phone_ad2f83_idx",
                    )
                ],
            },
        ),
    ]
