# Generated by Django 4.2.16 on 2026-05-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_backfill_check_in_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="churn_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="customer",
            name="cohort",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("active", "Active"),
                    ("at_risk", "At risk"),
                    ("dormant", "Dormant"),
                    ("lost", "Lost"),
                ],
                default="new",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="retention_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["cohort"], name="customer_cohort_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["churn_score"], name="customer_churn_score_idx"),
        ),
    ]
